### PR TITLE
update README

### PR DESCRIPTION
**Pull request by iblis17**

### CODE REVIEW

**Comment by JobJob** [comment]
This one, I was gonna say - maybe add a section before Installation Pre-requisites, with something like: 

a working installation of gym in python
PyCall set up correctly

**Comment by JobJob** [comment]
but I guess I missed the boat ⛵️

**Comment by iblis17** [comment]
oh, can re-arrange the section about Python gym

**Comment by JobJob** [comment]
Maybe just add a link to the section on installing the gym:

Pre-requisites: a working gym install that PyCall can find - see [install gym](https://github.com/JuliaML/OpenAIGym.jl#install-gym) below.

**Comment by iblis17** [comment]
I already opened an PR #19,
feel free to commit to that branch.

**Pull request merged**
