### PR TITLE
Speed part 2

### PR DESCRIPTION
**Pull request by JobJob**
Uses `setdata!` from https://github.com/JuliaPy/PyCall.jl/pull/487 which just updates the pointer to the data of the env.state PyArray, rather than creating a new PyArray each step.

requires 
* ~https://github.com/JuliaML/Reinforce.jl/pull/23~ (merged)
* https://github.com/JuliaPy/PyCall.jl/pull/487 (merged, awaiting release)

This is just one extra small commit on top of #11

### CODE REVIEW

**Comment by iblis17** [comment]
could you rebase this?

**Comment by JobJob** [comment]
Done, now we're just waiting on https://github.com/JuliaPy/PyCall.jl/pull/487  📅

**Comment by iblis17** [comment]
Okay.
After that PR merged, we still need to wait until new release tagged.

**Comment by baggepinnen** [comment]
Any obstacles left to merging these two PRs?

**Pull request merged**
